[build-system]
requires = [
    "setuptools>=40.8.0",
    "wheel",
    "Cython"
]

[tool.cibuildwheel]
build-frontend = "build[uv]"
enable = ["cpython-freethreading"]
environment-pass = ["SETUPTOOLS_SCM_PRETEND_VERSION"]
